import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class AbbreviationTest {
    @Test
    public void abbreviation_SimpleInput_ReturnCorrectResult(){
        String actual = Abbreviation.abbreviation("JSKKKPVEIKELNYFFaAPIFjzzswzguxgyxtfwihsbbrbnhqrqfhvilbhisifdfymuhnjpeplqxhgygbrmxkqvavhpvzupyfarttbavieetuqgokibzwriaroxyxuflxhftzzydpilikmdsxwlcfsshpmshhselchirblbkjutgctiwdoesgxhnfobwhsavehtvmjudlvkkkxowynjrufqvmczkeuktlhxvgzwcceguelipbtredjgcuhyuzuvvtkljlnfdjkouwbykkiyuqdymyvcmxzshdcnihvpxdjsrmeztshijnalnxfckrrpeppfpgmxtkinylgnkgnhorrfjdozdjtntoovqfdrvxzvsbsdyibkkimydxjpiagtydkyfzkdhtzorwosdtrxhraxqdzgtokthxerbcufawndvmwcjayonhldszdytfzdfbztdhzdylgokvulgmeadoivxzirhnncipyswsvvawwzqtinowejyspwgxvfzdwyoysqaqmhmlgedvckvaetggxukonuhzkfvvvrzxdpioffcreanvtyhkulxejdgxxxdlzwosuehzyhthezisipyoeibicozjpkglntmqkaaxalpfapgsiykkhcibyqmjoxxjgipprjfwabdncyhcutsitqzkadaufsactektrwqvjdpqgyjlvpiwyxfkgteyfffzefxngqctmntytwhgywqamfwtdkebujupwvcbtrdrmpshpztdehtxdleidscvhrariknfeumocebntrnrcmujrykinldwtvopxzqpkmtansbatxeffxqirysemxygcokgvafrdyegwnuowtqxywhilocfltbfnvtjcvhbtjitacqqqgdcvdlvmzmdbqxaemppntrtpzpchlqcohpqjrfecvufzkwzxmkdxsswbeyqkhluhhwlqofvybcqufcuwyhbdnyemjcpvqngfy", "JSKKKPVEIKELNYFFAPIF" +
                "");

        assertThat(actual).isEqualTo("YES");
    }
}
